// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEYqO6Cz3LyRuuRuO19TUtS4Xzb7Bz1ZU',
    appId: '1:405649942605:web:c96f18bf590e1d911c1404',
    messagingSenderId: '405649942605',
    projectId: 'dealmeet-c7ba3',
    authDomain: 'dealmeet-c7ba3.firebaseapp.com',
    storageBucket: 'dealmeet-c7ba3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPwcIR66-Zq5zv_D_UeBCIV6A46LZqx0',
    appId: '1:405649942605:android:53e453cb24e0a4451c1404',
    messagingSenderId: '405649942605',
    projectId: 'dealmeet-c7ba3',
    storageBucket: 'dealmeet-c7ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV25WnziguGFenOagnUts6-VGLyu61Lq8',
    appId: '1:405649942605:ios:9f86ae924136d2731c1404',
    messagingSenderId: '405649942605',
    projectId: 'dealmeet-c7ba3',
    storageBucket: 'dealmeet-c7ba3.appspot.com',
    iosBundleId: 'com.example.dealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV25WnziguGFenOagnUts6-VGLyu61Lq8',
    appId: '1:405649942605:ios:9f86ae924136d2731c1404',
    messagingSenderId: '405649942605',
    projectId: 'dealmeet-c7ba3',
    storageBucket: 'dealmeet-c7ba3.appspot.com',
    iosBundleId: 'com.example.dealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEYqO6Cz3LyRuuRuO19TUtS4Xzb7Bz1ZU',
    appId: '1:405649942605:web:e9833b24fdf4575f1c1404',
    messagingSenderId: '405649942605',
    projectId: 'dealmeet-c7ba3',
    authDomain: 'dealmeet-c7ba3.firebaseapp.com',
    storageBucket: 'dealmeet-c7ba3.appspot.com',
  );
}
